import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * Minimal dotenv-compatible parser.
 *
 * Supports:
 * - `KEY=value` and `export KEY=value`
 * - single- and double-quoted values (quotes stripped)
 * - `#` line comments and blank lines
 * - lowercase `key=` / `secret=` pairs (OPNsense "Download as .txt" format) are
 *   additionally mapped to `OPNSENSE_API_KEY` / `OPNSENSE_API_SECRET` so the
 *   file generated by OPNsense can be used as-is
 *
 * Does NOT support: multi-line values, variable interpolation, escape sequences.
 * This is intentional — the file is meant to hold simple key/value secrets, not
 * shell expressions.
 */
export function parseSecretsFile(contents: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const withoutExport = line.startsWith("export ") ? line.slice(7).trim() : line;
    const eq = withoutExport.indexOf("=");
    if (eq <= 0) continue;

    const key = withoutExport.slice(0, eq).trim();
    let value = withoutExport.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2)
    ) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  // OPNsense "Download as .txt" compatibility: the file contains two lines
  // `key=...` and `secret=...`. Map them to the env var names the client reads.
  if (result["key"] !== undefined && result["OPNSENSE_API_KEY"] === undefined) {
    result["OPNSENSE_API_KEY"] = result["key"];
  }
  if (result["secret"] !== undefined && result["OPNSENSE_API_SECRET"] === undefined) {
    result["OPNSENSE_API_SECRET"] = result["secret"];
  }

  return result;
}

/** Expand a leading `~` to the current user's home directory. */
export function expandTilde(filePath: string): string {
  if (filePath === "~") return os.homedir();
  if (filePath.startsWith("~/")) return path.join(os.homedir(), filePath.slice(2));
  return filePath;
}

/**
 * Load key/value pairs from the file pointed to by `MCP_SECRETS_FILE` (if set)
 * into `process.env`. Existing `process.env` entries take precedence — this is
 * additive and non-breaking for callers that already populate the environment
 * via a shell.
 *
 * Silent no-op if the env var is unset or the file does not exist. Never logs
 * the file path or its contents.
 */
export function loadSecretsFile(env: NodeJS.ProcessEnv = process.env): void {
  const configured = env["MCP_SECRETS_FILE"];
  if (!configured) return;

  const resolved = expandTilde(configured);

  let contents: string;
  try {
    contents = fs.readFileSync(resolved, "utf8");
  } catch {
    // Missing / unreadable file is not a fatal error — the server will still
    // read from process.env and fail later with a clear message if required
    // vars are missing.
    return;
  }

  const parsed = parseSecretsFile(contents);
  for (const [key, value] of Object.entries(parsed)) {
    if (env[key] === undefined || env[key] === "") {
      env[key] = value;
    }
  }
}
